# Generated by Django 5.2.5 on 2025-09-01 13:45

import django.core.validators
import points.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='points_poin_latitud_136fe3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=points.models.generate_share_slug, max_length=36, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('points', models.ManyToManyField(related_name='shares', to='points.point')),
            ],
            options={
                'verbose_name': 'Подборка (Share)',
                'verbose_name_plural': 'Подборки (Shares)',
            },
        ),
    ]
